[package]
name = "hpo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"
log = "0.4"

[dev-dependencies]
rayon = "1.6.0"