[package]
name = "hpo"
version = "0.1.0"
edition = "2021"
authors = ["Jonas Marcello <jonas.marcello@esbme.com>"]
description = "Human Phenotyoe Ontology Similarity"
readme = "README.md"
homepage = "https://github.com/anergictcell/hpo"
repository = "https://github.com/anergictcell/hpo"
license = "MIT"
keywords = ["human phenotype ontology", "phenomics", "ontology", "omim", "similarity"]
categories = ["science", "data-structures", "parser-implementations"]


[dependencies]
thiserror = "1.0.37"
log = "0.4"

[dev-dependencies]
rayon = "1.6.0"