name: Check merging to main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Format and Clippy
      run: cargo fmt --check && cargo clippy
    - name: Run tests
      run: cargo test
    - name: Check that docs build
      run: cargo doc
